"""baseline

Revision ID: 0001
Revises:
Create Date: 2026-07-15 00:23:32.055551

"""

import pgvector.sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "catalog_entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("url", sa.String(length=2048), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("site_url", sa.String(length=2048), nullable=True),
        sa.Column("category", sa.String(length=64), nullable=False),
        sa.Column(
            "source", sa.String(length=64), server_default="awesome-rss-feeds", nullable=False
        ),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "health_status", sa.String(length=24), server_default="unchecked", nullable=False
        ),
        sa.Column("checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("item_count", sa.Integer(), nullable=True),
        sa.Column("latest_item_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("final_url", sa.String(length=2048), nullable=True),
        sa.Column("content_type", sa.String(length=120), nullable=True),
        sa.Column(
            "preview_items",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_catalog_entries_category"), "catalog_entries", ["category"], unique=False
    )
    op.create_index(
        op.f("ix_catalog_entries_health_status"), "catalog_entries", ["health_status"], unique=False
    )
    op.create_index(
        op.f("ix_catalog_entries_is_active"), "catalog_entries", ["is_active"], unique=False
    )
    op.create_index(op.f("ix_catalog_entries_url"), "catalog_entries", ["url"], unique=True)
    op.create_table(
        "entities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("canonical_key", sa.String(length=512), nullable=False),
        sa.Column("url", sa.String(length=2048), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("kind", "canonical_key"),
    )
    op.create_index(op.f("ix_entities_kind"), "entities", ["kind"], unique=False)
    op.create_table(
        "feeds",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("url", sa.String(length=2048), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("site_url", sa.String(length=2048), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("last_fetched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("refresh_interval_minutes", sa.Integer(), nullable=False),
        sa.Column("ai_enabled", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("image_gen_enabled", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_feeds_url"), "feeds", ["url"], unique=True)
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("username", sa.String(length=30), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("password_hash", sa.String(length=128), nullable=False),
        sa.Column("default_view", sa.String(length=16), server_default="cards", nullable=False),
        sa.Column("image_prompt", sa.Text(), nullable=True),
        sa.Column("image_gen_monthly_limit", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "articles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("feed_id", sa.Integer(), nullable=False),
        sa.Column("guid", sa.String(length=1024), nullable=False),
        sa.Column("url", sa.String(length=2048), nullable=False),
        sa.Column("comments_url", sa.String(length=2048), nullable=True),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("author", sa.String(length=255), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("content_html", sa.Text(), nullable=False),
        sa.Column("excerpt", sa.Text(), nullable=False),
        sa.Column("image_url", sa.String(length=2048), nullable=True),
        sa.Column(
            "fetched_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("full_text", sa.Text(), server_default="", nullable=False),
        sa.Column("full_text_fetched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("summary_short", sa.Text(), server_default="", nullable=False),
        sa.Column("summary_medium", sa.Text(), server_default="", nullable=False),
        sa.Column("summary", sa.Text(), server_default="", nullable=False),
        sa.Column("summary_model", sa.String(length=120), nullable=True),
        sa.Column("summary_generated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("entities_extracted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ner_extracted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("image_gen_attempted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("image_gen_user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["feed_id"], ["feeds.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["image_gen_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("feed_id", "guid"),
    )
    op.create_index(op.f("ix_articles_feed_id"), "articles", ["feed_id"], unique=False)
    op.create_index(
        "ix_articles_feed_published", "articles", ["feed_id", "published_at"], unique=False
    )
    op.create_index(op.f("ix_articles_published_at"), "articles", ["published_at"], unique=False)
    op.create_table(
        "catalog_entry_embeddings",
        sa.Column("catalog_entry_id", sa.Integer(), nullable=False),
        sa.Column("model", sa.String(length=120), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(), nullable=False),
        sa.Column(
            "embedded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["catalog_entry_id"], ["catalog_entries.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("catalog_entry_id"),
    )
    op.create_table(
        "catalog_submissions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("url", sa.String(length=2048), nullable=False),
        sa.Column("category", sa.String(length=64), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=16), server_default="pending", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("url"),
    )
    op.create_index(
        op.f("ix_catalog_submissions_user_id"), "catalog_submissions", ["user_id"], unique=False
    )
    op.create_table(
        "devices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("push_token", sa.String(length=512), nullable=False),
        sa.Column("platform", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_devices_push_token"), "devices", ["push_token"], unique=True)
    op.create_index(op.f("ix_devices_user_id"), "devices", ["user_id"], unique=False)
    op.create_table(
        "entity_snapshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("entity_id", sa.Integer(), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "captured_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["entity_id"], ["entities.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_entity_snapshots_entity_captured",
        "entity_snapshots",
        ["entity_id", "captured_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_entity_snapshots_entity_id"), "entity_snapshots", ["entity_id"], unique=False
    )
    op.create_table(
        "llm_usage",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("feature", sa.String(length=16), nullable=False),
        sa.Column("provider", sa.String(length=16), nullable=False),
        sa.Column("model", sa.String(length=120), nullable=False),
        sa.Column("prompt_tokens", sa.Integer(), nullable=False),
        sa.Column("completion_tokens", sa.Integer(), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=8), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_llm_usage_user_created", "llm_usage", ["user_id", "created_at"], unique=False
    )
    op.create_index(op.f("ix_llm_usage_user_id"), "llm_usage", ["user_id"], unique=False)
    op.create_table(
        "messaging_connections",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("platform", sa.String(length=16), nullable=False),
        sa.Column("external_account_id", sa.String(length=255), nullable=False),
        sa.Column("account_name", sa.String(length=255), nullable=False),
        sa.Column("workspace_id", sa.String(length=255), nullable=False),
        sa.Column("workspace_name", sa.String(length=255), nullable=False),
        sa.Column("access_token_enc", sa.Text(), nullable=False),
        sa.Column("refresh_token_enc", sa.Text(), nullable=True),
        sa.Column("token_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("scopes", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "platform"),
    )
    op.create_index(
        op.f("ix_messaging_connections_user_id"), "messaging_connections", ["user_id"], unique=False
    )
    op.create_table(
        "projects",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), server_default="", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_projects_owner_id"), "projects", ["owner_id"], unique=False)
    op.create_table(
        "subscriptions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("feed_id", sa.Integer(), nullable=False),
        sa.Column("view_override", sa.String(length=16), nullable=True),
        sa.Column("title_override", sa.String(length=512), nullable=True),
        sa.Column("sort_order", sa.String(length=16), nullable=True),
        sa.Column("retention_days", sa.Integer(), nullable=True),
        sa.Column("is_muted", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["feed_id"], ["feeds.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "feed_id"),
    )
    op.create_index(op.f("ix_subscriptions_feed_id"), "subscriptions", ["feed_id"], unique=False)
    op.create_index(op.f("ix_subscriptions_user_id"), "subscriptions", ["user_id"], unique=False)
    op.create_table(
        "user_ai_settings",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=16), nullable=False),
        sa.Column("api_key_enc", sa.Text(), nullable=False),
        sa.Column("key_hint", sa.String(length=8), nullable=False),
        sa.Column("base_url", sa.String(length=2048), nullable=False),
        sa.Column("model", sa.String(length=120), nullable=False),
        sa.Column("supports_vision", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("image_provider", sa.String(length=16), nullable=True),
        sa.Column("image_model", sa.String(length=120), nullable=True),
        sa.Column("image_api_key_enc", sa.Text(), nullable=True),
        sa.Column("image_key_hint", sa.String(length=8), nullable=True),
        sa.Column("image_base_url", sa.String(length=2048), nullable=True),
        sa.Column("image_extra_params", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "user_reading_positions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("scope", sa.String(length=32), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("article_id", sa.Integer(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "scope"),
    )
    op.create_index(
        op.f("ix_user_reading_positions_user_id"),
        "user_reading_positions",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "article_embeddings",
        sa.Column("article_id", sa.Integer(), nullable=False),
        sa.Column("model", sa.String(length=120), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(), nullable=False),
        sa.Column(
            "embedded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("input_hash", sa.String(length=32), nullable=True),
        sa.ForeignKeyConstraint(["article_id"], ["articles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("article_id"),
    )
    op.create_table(
        "article_entities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("article_id", sa.Integer(), nullable=False),
        sa.Column("entity_id", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=8), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["article_id"], ["articles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["entity_id"], ["entities.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("article_id", "entity_id"),
    )
    op.create_index(
        op.f("ix_article_entities_article_id"), "article_entities", ["article_id"], unique=False
    )
    op.create_index(
        op.f("ix_article_entities_entity_id"), "article_entities", ["entity_id"], unique=False
    )
    op.create_table(
        "conversations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("article_id", sa.Integer(), nullable=True),
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=16), server_default="article", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["article_id"], ["articles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_conversations_article_id"), "conversations", ["article_id"], unique=False
    )
    op.create_index(
        op.f("ix_conversations_project_id"), "conversations", ["project_id"], unique=False
    )
    op.create_index(op.f("ix_conversations_user_id"), "conversations", ["user_id"], unique=False)
    op.create_index(
        "uq_conversations_article_user_kind",
        "conversations",
        ["article_id", "user_id", "kind"],
        unique=True,
        postgresql_where=sa.text("article_id IS NOT NULL"),
    )
    op.create_index(
        "uq_conversations_project_user",
        "conversations",
        ["project_id", "user_id"],
        unique=True,
        postgresql_where=sa.text("project_id IS NOT NULL"),
    )
    op.create_table(
        "external_shares",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("article_id", sa.Integer(), nullable=False),
        sa.Column("platform", sa.String(length=16), nullable=False),
        sa.Column("target_display", sa.String(length=255), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["article_id"], ["articles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_external_shares_article_id"), "external_shares", ["article_id"], unique=False
    )
    op.create_index(
        op.f("ix_external_shares_user_id"), "external_shares", ["user_id"], unique=False
    )
    op.create_table(
        "generated_images",
        sa.Column("article_id", sa.Integer(), nullable=False),
        sa.Column("content_type", sa.String(length=64), nullable=False),
        sa.Column("data", sa.LargeBinary(), nullable=False),
        sa.Column("model", sa.String(length=120), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["article_id"], ["articles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("article_id"),
    )
    op.create_table(
        "project_article_comments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("article_id", sa.Integer(), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("link_url", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["article_id"], ["articles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["author_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_project_article_comments_article_id"),
        "project_article_comments",
        ["article_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_article_comments_author_id"),
        "project_article_comments",
        ["author_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_article_comments_project_id"),
        "project_article_comments",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        "ix_project_article_comments_thread",
        "project_article_comments",
        ["project_id", "article_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "project_article_states",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("article_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("updated_by_user_id", sa.Integer(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["article_id"], ["articles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["updated_by_user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "article_id"),
    )
    op.create_index(
        op.f("ix_project_article_states_article_id"),
        "project_article_states",
        ["article_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_article_states_project_id"),
        "project_article_states",
        ["project_id"],
        unique=False,
    )
    op.create_table(
        "project_articles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("article_id", sa.Integer(), nullable=False),
        sa.Column("added_by_user_id", sa.Integer(), nullable=False),
        sa.Column("is_shared", sa.Boolean(), nullable=False),
        sa.Column("shared_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["added_by_user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["article_id"], ["articles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "article_id", "added_by_user_id"),
    )
    op.create_index(
        op.f("ix_project_articles_added_by_user_id"),
        "project_articles",
        ["added_by_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_articles_article_id"), "project_articles", ["article_id"], unique=False
    )
    op.create_index(
        op.f("ix_project_articles_project_id"), "project_articles", ["project_id"], unique=False
    )
    op.create_table(
        "project_members",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(length=12), nullable=False),
        sa.Column("last_visited_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_muted", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "user_id"),
    )
    op.create_index(
        op.f("ix_project_members_project_id"), "project_members", ["project_id"], unique=False
    )
    op.create_index(
        op.f("ix_project_members_user_id"), "project_members", ["user_id"], unique=False
    )
    op.create_table(
        "reading_activity",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("article_id", sa.Integer(), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("source", sa.String(length=8), nullable=False),
        sa.Column("seconds", sa.Integer(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["article_id"], ["articles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "article_id", "day", "source"),
    )
    op.create_index(
        op.f("ix_reading_activity_article_id"), "reading_activity", ["article_id"], unique=False
    )
    op.create_index(
        "ix_reading_activity_user_day", "reading_activity", ["user_id", "day"], unique=False
    )
    op.create_index(
        op.f("ix_reading_activity_user_id"), "reading_activity", ["user_id"], unique=False
    )
    op.create_table(
        "share_targets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("connection_id", sa.Integer(), nullable=False),
        sa.Column("target_type", sa.String(length=16), nullable=False),
        sa.Column("external_id", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["connection_id"], ["messaging_connections.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("connection_id", "external_id"),
    )
    op.create_index(
        op.f("ix_share_targets_connection_id"), "share_targets", ["connection_id"], unique=False
    )
    op.create_index(op.f("ix_share_targets_user_id"), "share_targets", ["user_id"], unique=False)
    op.create_table(
        "shares",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("from_user_id", sa.Integer(), nullable=False),
        sa.Column("article_id", sa.Integer(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["article_id"], ["articles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["from_user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_shares_article_id"), "shares", ["article_id"], unique=False)
    op.create_index(op.f("ix_shares_from_user_id"), "shares", ["from_user_id"], unique=False)
    op.create_table(
        "user_article_states",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("article_id", sa.Integer(), nullable=False),
        sa.Column("is_read", sa.Boolean(), nullable=False),
        sa.Column("is_saved", sa.Boolean(), nullable=False),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("read_source", sa.String(length=16), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["article_id"], ["articles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "article_id"),
    )
    op.create_index(
        op.f("ix_user_article_states_article_id"),
        "user_article_states",
        ["article_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_article_states_user_id"), "user_article_states", ["user_id"], unique=False
    )
    op.create_table(
        "user_dislike_rules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("article_id", sa.Integer(), nullable=True),
        sa.Column("entity_id", sa.Integer(), nullable=True),
        sa.Column("phrase", sa.Text(), nullable=True),
        sa.Column("label", sa.String(length=512), nullable=False),
        sa.Column("threshold", sa.Float(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["article_id"], ["articles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["entity_id"], ["entities.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_dislike_rules_article_id"), "user_dislike_rules", ["article_id"], unique=False
    )
    op.create_index(
        op.f("ix_user_dislike_rules_entity_id"), "user_dislike_rules", ["entity_id"], unique=False
    )
    op.create_index(
        op.f("ix_user_dislike_rules_user_id"), "user_dislike_rules", ["user_id"], unique=False
    )
    op.create_index(
        "uq_dislike_user_entity",
        "user_dislike_rules",
        ["user_id", "entity_id"],
        unique=True,
        postgresql_where=sa.text("entity_id IS NOT NULL"),
    )
    op.create_index(
        "uq_dislike_user_kind_article",
        "user_dislike_rules",
        ["user_id", "kind", "article_id"],
        unique=True,
        postgresql_where=sa.text("article_id IS NOT NULL"),
    )
    op.create_index(
        "uq_dislike_user_phrase",
        "user_dislike_rules",
        ["user_id", sa.literal_column("lower(phrase)")],
        unique=True,
        postgresql_where=sa.text("phrase IS NOT NULL"),
    )
    op.create_table(
        "article_suppressions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("article_id", sa.Integer(), nullable=False),
        sa.Column("rule_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["article_id"], ["articles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["rule_id"], ["user_dislike_rules.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "article_id", "rule_id"),
    )
    op.create_index(
        op.f("ix_article_suppressions_article_id"),
        "article_suppressions",
        ["article_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_article_suppressions_rule_id"), "article_suppressions", ["rule_id"], unique=False
    )
    op.create_table(
        "dislike_rule_embeddings",
        sa.Column("rule_id", sa.Integer(), nullable=False),
        sa.Column("model", sa.String(length=120), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["rule_id"], ["user_dislike_rules.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("rule_id"),
    )
    op.create_table(
        "messages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("conversation_id", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(length=12), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("tool_events", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["conversation_id"], ["conversations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_messages_conversation_id"), "messages", ["conversation_id"], unique=False
    )
    op.create_table(
        "share_recipients",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("share_id", sa.Integer(), nullable=False),
        sa.Column("to_user_id", sa.Integer(), nullable=False),
        sa.Column("seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["share_id"], ["shares.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["to_user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("share_id", "to_user_id"),
    )
    op.create_index(
        op.f("ix_share_recipients_share_id"), "share_recipients", ["share_id"], unique=False
    )
    op.create_index(
        op.f("ix_share_recipients_to_user_id"), "share_recipients", ["to_user_id"], unique=False
    )
    # --- Hand-written: schema pieces the ORM doesn't model ---

    # Keyword leg of hybrid article search (the semantic leg is article_embeddings).
    op.execute(
        "ALTER TABLE articles ADD COLUMN search_tsv tsvector GENERATED ALWAYS AS "
        "(to_tsvector('english', coalesce(title, '') || ' ' || coalesce(excerpt, '') || ' ' "
        "|| coalesce(summary_medium, ''))) STORED"
    )
    op.execute("CREATE INDEX ix_articles_search_tsv ON articles USING gin (search_tsv)")

    # Catalog full-text search; the vector leg lives in catalog_entry_embeddings.
    op.execute(
        "ALTER TABLE catalog_entries ADD COLUMN search_tsv tsvector GENERATED ALWAYS AS "
        "(setweight(to_tsvector('english', coalesce(title, '')), 'A') || "
        "setweight(to_tsvector('english', coalesce(description, '')), 'B') || "
        "setweight(to_tsvector('english', coalesce(category, '') || ' ' || coalesce(site_url, '') || ' ' || coalesce(url, '')), 'C')) STORED"
    )
    op.execute(
        "CREATE INDEX ix_catalog_entries_search_tsv ON catalog_entries USING gin (search_tsv)"
    )
    op.create_index(
        "ix_catalog_entries_active_category", "catalog_entries", ["is_active", "category"]
    )

    # Once-per-database data repairs claimed by init_db (see app/db.py).
    op.execute(
        "CREATE TABLE one_shot_migrations "
        "(name TEXT PRIMARY KEY, applied_at TIMESTAMPTZ NOT NULL DEFAULT now())"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("one_shot_migrations")
    op.drop_index("ix_catalog_entries_active_category", table_name="catalog_entries")
    op.drop_index(op.f("ix_share_recipients_to_user_id"), table_name="share_recipients")
    op.drop_index(op.f("ix_share_recipients_share_id"), table_name="share_recipients")
    op.drop_table("share_recipients")
    op.drop_index(op.f("ix_messages_conversation_id"), table_name="messages")
    op.drop_table("messages")
    op.drop_table("dislike_rule_embeddings")
    op.drop_index(op.f("ix_article_suppressions_rule_id"), table_name="article_suppressions")
    op.drop_index(op.f("ix_article_suppressions_article_id"), table_name="article_suppressions")
    op.drop_table("article_suppressions")
    op.drop_index(
        "uq_dislike_user_phrase",
        table_name="user_dislike_rules",
        postgresql_where=sa.text("phrase IS NOT NULL"),
    )
    op.drop_index(
        "uq_dislike_user_kind_article",
        table_name="user_dislike_rules",
        postgresql_where=sa.text("article_id IS NOT NULL"),
    )
    op.drop_index(
        "uq_dislike_user_entity",
        table_name="user_dislike_rules",
        postgresql_where=sa.text("entity_id IS NOT NULL"),
    )
    op.drop_index(op.f("ix_user_dislike_rules_user_id"), table_name="user_dislike_rules")
    op.drop_index(op.f("ix_user_dislike_rules_entity_id"), table_name="user_dislike_rules")
    op.drop_index(op.f("ix_user_dislike_rules_article_id"), table_name="user_dislike_rules")
    op.drop_table("user_dislike_rules")
    op.drop_index(op.f("ix_user_article_states_user_id"), table_name="user_article_states")
    op.drop_index(op.f("ix_user_article_states_article_id"), table_name="user_article_states")
    op.drop_table("user_article_states")
    op.drop_index(op.f("ix_shares_from_user_id"), table_name="shares")
    op.drop_index(op.f("ix_shares_article_id"), table_name="shares")
    op.drop_table("shares")
    op.drop_index(op.f("ix_share_targets_user_id"), table_name="share_targets")
    op.drop_index(op.f("ix_share_targets_connection_id"), table_name="share_targets")
    op.drop_table("share_targets")
    op.drop_index(op.f("ix_reading_activity_user_id"), table_name="reading_activity")
    op.drop_index("ix_reading_activity_user_day", table_name="reading_activity")
    op.drop_index(op.f("ix_reading_activity_article_id"), table_name="reading_activity")
    op.drop_table("reading_activity")
    op.drop_index(op.f("ix_project_members_user_id"), table_name="project_members")
    op.drop_index(op.f("ix_project_members_project_id"), table_name="project_members")
    op.drop_table("project_members")
    op.drop_index(op.f("ix_project_articles_project_id"), table_name="project_articles")
    op.drop_index(op.f("ix_project_articles_article_id"), table_name="project_articles")
    op.drop_index(op.f("ix_project_articles_added_by_user_id"), table_name="project_articles")
    op.drop_table("project_articles")
    op.drop_index(op.f("ix_project_article_states_project_id"), table_name="project_article_states")
    op.drop_index(op.f("ix_project_article_states_article_id"), table_name="project_article_states")
    op.drop_table("project_article_states")
    op.drop_index("ix_project_article_comments_thread", table_name="project_article_comments")
    op.drop_index(
        op.f("ix_project_article_comments_project_id"), table_name="project_article_comments"
    )
    op.drop_index(
        op.f("ix_project_article_comments_author_id"), table_name="project_article_comments"
    )
    op.drop_index(
        op.f("ix_project_article_comments_article_id"), table_name="project_article_comments"
    )
    op.drop_table("project_article_comments")
    op.drop_table("generated_images")
    op.drop_index(op.f("ix_external_shares_user_id"), table_name="external_shares")
    op.drop_index(op.f("ix_external_shares_article_id"), table_name="external_shares")
    op.drop_table("external_shares")
    op.drop_index(
        "uq_conversations_project_user",
        table_name="conversations",
        postgresql_where=sa.text("project_id IS NOT NULL"),
    )
    op.drop_index(
        "uq_conversations_article_user_kind",
        table_name="conversations",
        postgresql_where=sa.text("article_id IS NOT NULL"),
    )
    op.drop_index(op.f("ix_conversations_user_id"), table_name="conversations")
    op.drop_index(op.f("ix_conversations_project_id"), table_name="conversations")
    op.drop_index(op.f("ix_conversations_article_id"), table_name="conversations")
    op.drop_table("conversations")
    op.drop_index(op.f("ix_article_entities_entity_id"), table_name="article_entities")
    op.drop_index(op.f("ix_article_entities_article_id"), table_name="article_entities")
    op.drop_table("article_entities")
    op.drop_table("article_embeddings")
    op.drop_index(op.f("ix_user_reading_positions_user_id"), table_name="user_reading_positions")
    op.drop_table("user_reading_positions")
    op.drop_table("user_ai_settings")
    op.drop_index(op.f("ix_subscriptions_user_id"), table_name="subscriptions")
    op.drop_index(op.f("ix_subscriptions_feed_id"), table_name="subscriptions")
    op.drop_table("subscriptions")
    op.drop_index(op.f("ix_projects_owner_id"), table_name="projects")
    op.drop_table("projects")
    op.drop_index(op.f("ix_messaging_connections_user_id"), table_name="messaging_connections")
    op.drop_table("messaging_connections")
    op.drop_index(op.f("ix_llm_usage_user_id"), table_name="llm_usage")
    op.drop_index("ix_llm_usage_user_created", table_name="llm_usage")
    op.drop_table("llm_usage")
    op.drop_index(op.f("ix_entity_snapshots_entity_id"), table_name="entity_snapshots")
    op.drop_index("ix_entity_snapshots_entity_captured", table_name="entity_snapshots")
    op.drop_table("entity_snapshots")
    op.drop_index(op.f("ix_devices_user_id"), table_name="devices")
    op.drop_index(op.f("ix_devices_push_token"), table_name="devices")
    op.drop_table("devices")
    op.drop_index(op.f("ix_catalog_submissions_user_id"), table_name="catalog_submissions")
    op.drop_table("catalog_submissions")
    op.drop_table("catalog_entry_embeddings")
    op.drop_index(op.f("ix_articles_published_at"), table_name="articles")
    op.drop_index("ix_articles_feed_published", table_name="articles")
    op.drop_index(op.f("ix_articles_feed_id"), table_name="articles")
    op.drop_table("articles")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_feeds_url"), table_name="feeds")
    op.drop_table("feeds")
    op.drop_index(op.f("ix_entities_kind"), table_name="entities")
    op.drop_table("entities")
    op.drop_index(op.f("ix_catalog_entries_url"), table_name="catalog_entries")
    op.drop_index(op.f("ix_catalog_entries_is_active"), table_name="catalog_entries")
    op.drop_index(op.f("ix_catalog_entries_health_status"), table_name="catalog_entries")
    op.drop_index(op.f("ix_catalog_entries_category"), table_name="catalog_entries")
    op.drop_table("catalog_entries")
    # ### end Alembic commands ###
