"""Runtime-managed HNSW indexes for the pgvector embedding columns (#81).

The embedding columns stay dimension-less Vector() — the dimension follows
whatever OPENAI_EMBEDDING_MODEL is configured, and rows for two models (two
dimensions) coexist while the worker re-embeds after a switch. pgvector cannot
build an HNSW index on such a column, but it can index a cast *expression*,
and a partial predicate keeps every other model's rows (whose dimension would
fail the cast) out of the index:

    CREATE INDEX ... ON <table> USING hnsw
        ((embedding::halfvec(<dim>)) halfvec_cosine_ops)
    WHERE model = '<configured model>'

halfvec (fp16) halves index size at negligible recall cost and lifts the
indexable-dimension ceiling from 2000 to 4000.

Because the model and its dimension are deployment configuration, the indexes
cannot live in an Alembic revision: the worker calls ensure_indexes() every
cycle instead. It is a cheap no-op when the configured model's index exists,
builds it once rows for that model appear, and drops indexes left behind by
previous models. (An autogenerated migration that dropped them would therefore
self-heal on the next cycle.)

Query sites opt in through knn_distance(), whose cast matches the index
expression. Sites that must rank EVERY row (no LIMIT — an HNSW scan ends
early and would drop rows) and the dislike-rule threshold join in
suppressions.py (WHERE distance < x across two columns, not a top-K) keep
plain cosine_distance and its exact scan on purpose; dislike_rule_embeddings
is not indexed at all for that reason.

Requires pgvector >= 0.8 for iterative index scans — without those, the
filters layered on every KNN here would silently thin the candidate pool to
ef_search. On older servers nothing is built and every query stays an exact
scan, exactly as before this module existed. Decision record and ops notes:
docs/ann-indexes.md.
"""

import hashlib
import logging

from pgvector.sqlalchemy import HALFVEC
from sqlalchemy import text

from . import db, embeddings
from .config import settings

logger = logging.getLogger(__name__)

INDEXED_TABLES = (
    "article_embeddings",
    "catalog_entry_embeddings",
    "browser_history_document_embeddings",
)
# pgvector's HNSW supports halfvec up to 4000 dimensions; a model beyond that
# simply stays on exact scans.
HNSW_MAX_DIM = 4000

# Whether the server's pgvector understands hnsw.iterative_scan (>= 0.8).
# Probed once per process on first use; None = not probed yet.
_capable: bool | None = None


def index_name(table: str, model: str, dim: int) -> str:
    digest = hashlib.md5(f"{model}:{dim}".encode()).hexdigest()[:8]
    return f"hnsw_{table}_{digest}"


def knn_distance(column, query_vector):
    """Cosine distance whose cast matches the HNSW index expression, so
    ORDER BY knn_distance(...) LIMIT n is index-served once the index exists
    (and an exact halfvec scan until then). Top-K queries only: an HNSW scan
    ends early, so ranking every row still needs plain cosine_distance."""
    return column.cast(HALFVEC(len(query_vector))).cosine_distance(query_vector)


async def _iterative_scan_available(session) -> bool:
    global _capable
    if _capable is None:
        version = await session.scalar(
            text("SELECT extversion FROM pg_extension WHERE extname = 'vector'")
        )
        parts = (version or "0").split(".")
        try:
            minor = int(parts[1]) if len(parts) > 1 else 0
            _capable = (int(parts[0]), minor) >= (0, 8)
        except ValueError:
            _capable = False
    return _capable


async def relax_scan(session) -> None:
    """SET LOCAL hnsw.iterative_scan for the current transaction: keep the
    index scan going past ef_search (in exact distance order) until the LIMIT
    is satisfied. Without it, the joins and filters layered on every KNN
    query here would thin the candidate pool to ef_search (default 40).
    No-op below pgvector 0.8 — where no index exists to scan anyway."""
    if await _iterative_scan_available(session):
        await session.execute(text("SET LOCAL hnsw.iterative_scan = 'strict_order'"))


async def ensure_indexes() -> None:
    """Worker-cycle hook: reconcile the HNSW indexes with the configured
    model. A first build on a large table blocks that table's writes for the
    build duration (ops notes in docs/ann-indexes.md); after that, upkeep is
    a few catalog lookups per cycle."""
    if not embeddings.is_configured():
        return
    model = settings.openai_embedding_model
    async with db.SessionLocal() as session:
        if not await _iterative_scan_available(session):
            return
        for table in INDEXED_TABLES:
            try:
                dim = await session.scalar(
                    text(
                        f"SELECT vector_dims(embedding) FROM {table} "  # noqa: S608
                        "WHERE model = :model LIMIT 1"
                    ),
                    {"model": model},
                )
                expected = None
                if dim is not None and dim <= HNSW_MAX_DIM:
                    expected = index_name(table, model, dim)
                existing = set(
                    (
                        await session.scalars(
                            text(
                                "SELECT indexname FROM pg_indexes "
                                "WHERE schemaname = 'public' AND tablename = :table "
                                "AND indexname LIKE 'hnsw#_%' ESCAPE '#'"
                            ),
                            {"table": table},
                        )
                    ).all()
                )
                for stale in sorted(existing - {expected}):
                    await session.execute(text(f'DROP INDEX IF EXISTS "{stale}"'))
                if expected is not None and expected not in existing:
                    # Serial build: the parallel one allocates DSM segments
                    # sized by maintenance_work_mem, which overflows the 64MB
                    # /dev/shm of a default Docker container ("could not
                    # resize shared memory segment"). Serial keeps the graph
                    # in private memory, where a bigger budget is safe.
                    await session.execute(text("SET max_parallel_maintenance_workers = 0"))
                    await session.execute(text("SET maintenance_work_mem = '512MB'"))
                    # DDL takes no bind params; model comes from server config,
                    # quoted defensively all the same.
                    quoted_model = model.replace("'", "''")
                    await session.execute(
                        text(
                            f'CREATE INDEX IF NOT EXISTS "{expected}" ON {table} '
                            f"USING hnsw ((embedding::halfvec({dim})) halfvec_cosine_ops) "
                            f"WHERE model = '{quoted_model}'"
                        )
                    )
                    logger.info("Built HNSW index %s (dim %d)", expected, dim)
                await session.commit()
            except Exception as exc:
                logger.warning("HNSW index upkeep on %s failed: %s", table, exc)
                await session.rollback()
